### ISSUE TITLE
Issue with CA APM Browser Agent

### ISSUE THREAD

**Issue by Saurabh1311** [CA-APM/browser-agent-typeview#2]
After configuration of browser agent we found users are facing login issue or login window popup while they do any click on screen. Did anyone of you face this issue and have any solution please share

**Comment by ggrossbe** [comment]
Hi Saurabh,

This is a known issue. Please open a support case at https://support.ca.com and one of my colleagues will guide you to a solution.

Ciao,
Guenter

**Comment by Saurabh1311** [comment]
please find the case 00516868
